(* This module acts as an [import.ml] file for all the module tests that are siblings of
   this module. It is necessary because it creates scaffolding for the associated modules
   that needs to run prior to the side effects generated by [ppx_css] run. *)

include module type of Core
include module type of Bonsai_web_proc
include module type of Bonsai_web_test
module Test_fn = Instantiate_dummy_functions

val vdom_handle : Vdom.Node.t -> (Vdom.Node.t, never_returns) Handle.t
val css_attr_handle : Vdom.Attr.t -> (Vdom.Node.t, never_returns) Handle.t
val get_value : unit -> string
val print_css : unit -> unit
val compare_against_prev : unit -> unit
val clear_before_test : unit -> unit
